### ISSUE TITLE
Include symbols line - 2 issues

### ISSUE THREAD

**Issue by Lrt19** [BdR76/RandomValuesNPP#4]
First, great work on the plugin, very useful.
The default characters in the "Include symbols" line has semicolon twice, therefor the frequency distribution of ; will be twice that of the other characters.
Also, the generated code seems to ignore the last character on the "Include symbols" line. It will get 0 frequency. (default tilde ~)
Please keep the functionality where a user can type anything here, even multiple repeating letters to purposely skew the frequency distribution.
I could see use in this to hide a message in apparent randomness.
As an enhancement request; could it be possible for the plugin to save the users last settings?
Thank you!

**Comment by BdR76** [comment]
Sorry for the late reply. Not sure what you mean exactly with your comments though.

1) The default characters in the "Include symbols" line, I assume you mean the `VARCHAR_MASK_S` variable on [this line](https://github.com/BdR76/RandomValuesNPP/blob/main/RandomValuesNppPlugin/RandomValue.cs#L35)? The semicolon at the end of the line is part of the C# language, but I don't see any semicolon in the actual string.

2) The generated code ignores the last character on the "Include symbols" line? I assume this is also about the `VARCHAR_MASK_S` variable.  The last two character are a plus and a minus, there is no tilde. Maybe you mistook the minus for a tilde? I'll admit the default font is quite small.

3) The plugin does save the users settings, however on the Generate Values form it only saves when you actually generate the values and close with `OK`, it doesn't save the setting when you click `Cancel` to close.

Hope that answers you questions.

**Comment by Lrt19** [comment]
Sorry, I posted this on the wrong project completely.

**Comment by BdR76** [comment]
ha 😆 ok no worries
